import pyzmail, imapclient, os
conn = imapclient.IMAPClient('imap.gmail.com',ssl=True)
myEmail = os.environ.get('GMAIL')
myPass = os.environ.get('PYTHON_GMAIL_PASS')
conn.login(myEmail,myPass)
conn.select_folder('INBOX',readonly=True)
UIDs = conn.search('SINCE 15-Jan-2020')
rawMessage = conn.fetch([5370],['BODY[]','FLAGS'])
message = pyzmail.PyzMessage.factory(rawMessage[5370][b'BODY[]'])
print(message.get_subject())
print(message.text_part)
print(message.html_part)
print(message.text_part.get_payload().decode('utf-8'))
print(message.get_addresses('from'))